[project]
authors = ["Pierre Poulain <pierre.poulain@cupnet.net>"]
channels = ["conda-forge", "nodefaults"]
description = "Environment for LLM practicals"
name = "llm-practicals"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
compile = "jupyter-book build content"

[dependencies]
python = "3.11.*"
pip = "*"
numpy = "*"
jupyter-book = "*"
